# Deployment do Postgre
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
    template:
      metadata:
        labels:
            app: postgre
      spec:
        containers:
          - name: postgre
            image: postgre:14.3
            ports:
              - containerPort: 5432
            env:
              - name: POSTGRES_PASSWORD
                value: "kube#123"
              - name: POSTGRES_USER
                value: "kubenews"
              - name: POSTGRES_DB
                value: "kubenews"

---
# como o banco de dados dever ser acessivel para a aplicacao, vamos criar o service
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
  - port: 5432 # a porta que vai ser utilizada pelo service
    targetPort: 5432 # a porta que sera derecionada para o pod`:wq
    
