# This is a basic workflow to help you get started with Actions

name: CI-CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  CI:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # taking the code to the runs-on(ubuntu-latest
      - uses: actions/checkout@v3
      - name: Autenticando o usuario no Docker #Docker Login
        uses: docker/login-action@v2.0.0
        with:
          # Username used to log against the Docker registry
          # https://github.com/cabicho/kube-news/settings/secrets/actions/new
          username: ${{secrets.DOCKERHUB_USER}}
          # Password or personal access token used to log against the Docker registry
          password: ${{secrets.DOCKERHUB_PWD}}
          # Specifies whether the given registry is ECR (auto, true or false)
      - name: Construindo a imagem e enviando para o Docker Hub #Build and push Docker images
        uses: docker/build-push-action@v3.0.0
        with:
          file: ./src/Dockerfile
          context: ./src
          push: true
          tags: | # como vamos especificar mais de uma
            cabicho/kube-news:latest
            cabicho/kube-news:${{github.run_number}}
  CD:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [CI]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # taking the code to the runs-on(ubuntu-latest)
      - uses: actions/checkout@v3
      - name: Efectuando o Deploy no ambiente de teste Kubernetes #Kubernetes Set Context
        uses: Azure/k8s-set-context@v2
        with:
          # Marketplace/Search results/Kubernetes Set Context
          # Acceptable values: kubeconfig or service-account or service-principal
          method: kubeconfig  # default is kubeconfig
          # Contents of kubeconfig file
          kubeconfig: ${{secrets.K8S_CONFIG}} # optional, foi necessario actualizar        
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v3.1
        with:
          # Username used to log against the Docker registry
          # https://github.com/cabicho/kube-news/settings/secrets/actions/new
          images: cabicho/kube-news:${{github.run_number}}
          # Password or personal access token used to log against the Docker registry
          manifests: |
            k8s/deployment.yaml
      
